steps:
    - name: gcr.io/cloud-builders/docker
      env:
          - DOCKER_BUILDKIT=1 # これを書かないとビルドが失敗する
      entrypoint: "bash"
      args: [
              "-c",
              "docker build --no-cache -t $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA . -f Dockerfile --build-arg MICROCMS_SERVICE_DOMAIN=$$MICROCMS_SERVICE_DOMAIN --build-arg MICROCMS_API_KEY=$$MICROCMS_API_KEY --build-arg NEXT_PUBLIC_MEASUREMENT_ID=$$NEXT_PUBLIC_MEASUREMENT_ID --build-arg CONTACT_FORM_API_URL=$$CONTACT_FORM_API_URL",
          ] # 参考： https://qiita.com/ebatan-developer/items/d3ca8c0f72dbfba7821f
      secretEnv: [
              "MICROCMS_SERVICE_DOMAIN",
              "MICROCMS_API_KEY",
              "NEXT_PUBLIC_MEASUREMENT_ID",
              "CONTACT_FORM_API_URL",
          ] # 使用するシークレットはここに書かないといけない
      id: Build
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - >-
              $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      id: Push
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
      args:
          - run
          - services
          - update
          - $_SERVICE_NAME
          - "--platform=managed"
          - >-
              --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - >-
              --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
          - "--region=$_DEPLOY_REGION"
          - "--quiet"
      id: Deploy
      entrypoint: gcloud
# あらかじめ設定したシークレットを取得する
availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/MICROCMS_SERVICE_DOMAIN/versions/latest
          env: "MICROCMS_SERVICE_DOMAIN"
        - versionName: projects/$PROJECT_ID/secrets/MICROCMS_API_KEY/versions/latest
          env: "MICROCMS_API_KEY"
        - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_MEASUREMENT_ID/versions/latest
          env: "NEXT_PUBLIC_MEASUREMENT_ID"
        - versionName: projects/$PROJECT_ID/secrets/CONTACT_FORM_API_URL/versions/latest
          env: "CONTACT_FORM_API_URL"
images:
    - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
substitutions:
    _SERVICE_NAME: kyoto-univ-marketing-web
    _TRIGGER_ID: 17dd8aa3-cc3d-4a4a-bcb2-1def15c06d23
    _DEPLOY_REGION: asia-northeast1
    _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
    _PLATFORM: managed
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - kyoto-univ-marketing-web
