services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            # 参考： https://zenn.dev/nbstsh/scraps/05176d4ab59e48
            args:
                - MICROCMS_SERVICE_DOMAIN=${MICROCMS_SERVICE_DOMAIN}
                - MICROCMS_API_KEY=${MICROCMS_API_KEY}
                - NEXT_PUBLIC_MEASUREMENT_ID=${NEXT_PUBLIC_MEASUREMENT_ID}
                - CONTACT_FORM_API_URL=${CONTACT_FORM_API_URL}
        ports:
            - '3000:3000'
