/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/about_stats/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_about_stats_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/about_stats/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_about_stats_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project_links/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_links_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project_links/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_links_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/text/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_text_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/text/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_text_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/media/./': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['media_._retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        AboutStat: {
            readonly id: number
            /** タイトル */
            title: string
            /**
             * 数値
             * Format: int64
             */
            number: number
            /**
             * 更新日時
             * Format: date-time
             */
            readonly updated_at: string
        }
        /**
         * @description * `top_message` - トップページのメッセージ
         *     * `top_sub_message` - トップページのサブメッセージ
         *     * `circle_outline` - サークル概要
         *     * `origin` - 設立の経緯
         *     * `activity_description` - 活動記録ページの説明
         *     * `project_description` - プロジェクトページの説明
         *     * `contact_privacy` - お問い合わせ・個人情報について
         *     * `contact_description_for_others` - お問い合わせページの説明（企業・団体など向け）
         *     * `contact_description_for_kyodai` - お問い合わせページの説明（京大生向け）
         *     * `contact_success_message` - お問い合わせ完了メッセージ
         * @enum {string}
         */
        IdEnum:
            | 'top_message'
            | 'top_sub_message'
            | 'circle_outline'
            | 'origin'
            | 'activity_description'
            | 'project_description'
            | 'contact_privacy'
            | 'contact_description_for_others'
            | 'contact_description_for_kyodai'
            | 'contact_success_message'
        Project: {
            readonly id: number
            readonly links: components['schemas']['ProjectLinks'][]
            /** プロジェクト名 */
            name: string
            /** 説明 */
            description: string
            /**
             * サムネイル
             * Format: uri
             */
            thumbnail: string
            /** タグ */
            tag: components['schemas']['TagEnum']
            /**
             * 更新日時
             * Format: date-time
             */
            readonly updated_at: string
        }
        ProjectLinks: {
            readonly id: number
            /** タイトル */
            title?: string | null
            /** Format: uri */
            url: string
            /** プロジェクト */
            project: number
        }
        /**
         * @description * `マーケティング支援` - マーケティング支援
         *     * `共同プロジェクト` - 共同プロジェクト
         *     * `オリジナルプロジェクト` - オリジナルプロジェクト
         * @enum {string}
         */
        TagEnum: 'マーケティング支援' | '共同プロジェクト' | 'オリジナルプロジェクト'
        Text: {
            id: components['schemas']['IdEnum']
            /** テキスト */
            text: string
            /**
             * 更新日時
             * Format: date-time
             */
            readonly updated_at: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    api_about_stats_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['AboutStat'][]
                }
            }
        }
    }
    api_about_stats_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description A unique integer value identifying this サークル概要の統計情報. */
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['AboutStat']
                }
            }
        }
    }
    api_project_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Project'][]
                }
            }
        }
    }
    api_project_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description A unique integer value identifying this プロジェクト. */
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Project']
                }
            }
        }
    }
    api_project_links_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ProjectLinks'][]
                }
            }
        }
    }
    api_project_links_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description A unique integer value identifying this プロジェクト. */
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ProjectLinks']
                }
            }
        }
    }
    api_text_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Text'][]
                }
            }
        }
    }
    api_text_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                id:
                    | 'top_message'
                    | 'top_sub_message'
                    | 'circle_outline'
                    | 'origin'
                    | 'activity_description'
                    | 'project_description'
                    | 'contact_privacy'
                    | 'contact_description_for_others'
                    | 'contact_description_for_kyodai'
                    | 'contact_success_message'
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Text']
                }
            }
        }
    }
    'media_._retrieve': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
