/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/about_stats/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_about_stats_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/about_stats/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_about_stats_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project_links/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_links_list']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/project_links/{id}/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['api_project_links_retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/media/./': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['media_._retrieve']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        AboutStat: {
            readonly id: number
            /** タイトル */
            title: string
            /**
             * 数値
             * Format: int64
             */
            number: number
            /**
             * 更新日時
             * Format: date-time
             */
            readonly updated_at: string
        }
        Project: {
            readonly id: number
            readonly links: components['schemas']['ProjectLinks'][]
            /** プロジェクト名 */
            name: string
            /** 説明 */
            description: string
            /**
             * サムネイル
             * Format: uri
             */
            thumbnail: string
            /**
             * 更新日時
             * Format: date-time
             */
            readonly updated_at: string
        }
        ProjectLinks: {
            readonly id: number
            /** タイトル */
            title?: string | null
            /** Format: uri */
            url: string
            /** プロジェクト */
            project: number
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    api_about_stats_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['AboutStat'][]
                }
            }
        }
    }
    api_about_stats_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description A unique integer value identifying this サークル概要の統計情報. */
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['AboutStat']
                }
            }
        }
    }
    api_project_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Project'][]
                }
            }
        }
    }
    api_project_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description A unique integer value identifying this プロジェクト. */
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Project']
                }
            }
        }
    }
    api_project_links_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ProjectLinks'][]
                }
            }
        }
    }
    api_project_links_retrieve: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description A unique integer value identifying this プロジェクト. */
                id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ProjectLinks']
                }
            }
        }
    }
    'media_._retrieve': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
