# 参考： https://qiita.com/yanskun/items/f50421fae619b375f0e1

name: Deploy Storybook

on:
    push:
        branches:
            - main

jobs:
    deploy-storybook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'
            - name: install pnpm
              run: corepack enable
            - name: install packages
              run: pnpm install --frozen-lockfile
            - name: build storybook
              run: pnpm build-storybook
            - name: deploy storybook
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: storybook-static
