# 参考： https://qiita.com/yanskun/items/f50421fae619b375f0e1

name: Deploy Storybook

on:
    push:
        branches:
            - main

jobs:
    deploy-storybook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 'latest'
            - name: install packages
              run: bun install --frozen-lockfile
            - name: build storybook
              run: bun run build-storybook
            - name: deploy storybook
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: storybook-static
